// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_60000_meters = "CgkI2ZzGl84cEAIQCA"; // <GPGSID>
        public const string achievement_20000_meters = "CgkI2ZzGl84cEAIQBQ"; // <GPGSID>
        public const string achievement_100000_pionts = "CgkI2ZzGl84cEAIQDQ"; // <GPGSID>
        public const string achievement_200000_meters = "CgkI2ZzGl84cEAIQDA"; // <GPGSID>
        public const string achievement_30000_meters = "CgkI2ZzGl84cEAIQBg"; // <GPGSID>
        public const string achievement_100000_points = "CgkI2ZzGl84cEAIQDg"; // <GPGSID>
        public const string achievement_80000_meters = "CgkI2ZzGl84cEAIQCQ"; // <GPGSID>
        public const string achievement_40000_meters = "CgkI2ZzGl84cEAIQBw"; // <GPGSID>
        public const string achievement_15000_meters = "CgkI2ZzGl84cEAIQBA"; // <GPGSID>
        public const string achievement_300_meters = "CgkI2ZzGl84cEAIQAQ"; // <GPGSID>
        public const string achievement_150000_meters = "CgkI2ZzGl84cEAIQCw"; // <GPGSID>
        public const string leaderboard_highest_points = "CgkI2ZzGl84cEAIQEA"; // <GPGSID>
        public const string achievement_100000_meters = "CgkI2ZzGl84cEAIQCg"; // <GPGSID>
        public const string achievement_5000_meters = "CgkI2ZzGl84cEAIQAg"; // <GPGSID>
        public const string achievement_1000000_points = "CgkI2ZzGl84cEAIQDw"; // <GPGSID>
        public const string achievement_10000_meters = "CgkI2ZzGl84cEAIQAw"; // <GPGSID>

}

